homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /api
        permanent: true
authentication_token:
    path: /api/login
    methods: ['POST']